"""empty message

Revision ID: 8ee938077f80
Revises: 
Create Date: 2022-12-20 10:20:11.768937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee938077f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('book',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('pub_date', sa.String(length=10), nullable=True),
    sa.Column('more_info', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('pub_date', sa.String(length=10), nullable=True),
    sa.Column('more_info', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('book_history')
    op.drop_table('book')
    op.drop_table('user')
    # ### end Alembic commands ###
